[package]
name = "blockcar-genesis"
version = "0.1.0"
authors = ["PhdTrollSlayer <rodrigomauricio@protonmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
rustc-hex = "*"
openssl = "0.10.23"
base64 = "0.10.1"
rand = "*"
json = "0.11.14"
